In [2]:
import pandas as pd

In [3]:
filepath = 'Dataset/Consolidated/measurements_2017-01-01_2018-01-01.csv'

df = pd.read_csv(filepath)

In [5]:
df.head(5)

,Datetime,Flow (l/s) [Catchment 1],Flow (l/s) [Catchment 1] Quality,Flow (l/s) [Catchment 1] Quality Last Modified,Flow (l/s) [Catchment 2],Flow (l/s) [Catchment 2] Quality,Flow (l/s) [Catchment 2] Quality Last Modified,Flow (l/s) [Catchment 3],Flow (l/s) [Catchment 3] Quality,Flow (l/s) [Catchment 3] Quality Last Modified,...,Soil Moisture @ 10cm Depth (%) [Catchment 12] Quality Last Modified,Soil Moisture @ 10cm Depth (%) [Catchment 13],Soil Moisture @ 10cm Depth (%) [Catchment 13] Quality,Soil Moisture @ 10cm Depth (%) [Catchment 13] Quality Last Modified,Soil Moisture @ 10cm Depth (%) [Catchment 14],Soil Moisture @ 10cm Depth (%) [Catchment 14] Quality,Soil Moisture @ 10cm Depth (%) [Catchment 14] Quality Last Modified,Soil Moisture @ 10cm Depth (%) [Catchment 15],Soil Moisture @ 10cm Depth (%) [Catchment 15] Quality,Soil Moisture @ 10cm Depth (%) [Catchment 15] Quality Last Modified
0,2017/01/01 00:15:00,0.1414,Acceptable,2018/11/24,NaN,Not set,2018/11/22,NaN,Not set,2018/11/22,...,2018/11/24,NaN,Not set,2018/11/21,37.78,Acceptable,2018/11/24,37.25,Acceptable,2018/11/24
1,2017/01/01 00:30:00,0.1414,Acceptable,2018/11/24,NaN,Not set,2018/11/22,NaN,Not set,2018/11/22,...,2018/11/24,NaN,Not set,2018/11/21,37.80,Acceptable,2018/11/24,37.25,Acceptable,2018/11/24
2,2017/01/01 00:45:00,0.1414,Acceptable,2018/11/24,NaN,Not set,2018/11/22,0.07474,Acceptable,2018/11/24,...,2018/11/24,NaN,Not set,2018/11/21,37.78,Acceptable,2018/11/24,37.25,Acceptable,2018/11/24
3,2017/01/01 01:00:00,0.1414,Acceptable,2018/11/24,NaN,Not set,2018/11/22,NaN,Not set,2018/11/22,...,2018/11/24,NaN,Not set,2018/11/21,37.78,Acceptable,2018/11/24,37.25,Acceptable,2018/11/24
4,2017/01/01 01:15:00,0.1414,Acceptable,2018/11/24,NaN,Not set,2018/11/22,NaN,Not set,2018/11/22,...,2018/11/24,NaN,Not set,2018/11/21,37.78,Acceptable,2018/11/24,37.25,Acceptable,2018/11/24

In [8]:
filepath = 'Dataset/Consolidated/greenhouse_2017-01-01_2018-01-01.csv'

df = pd.read_csv(filepath)

In [9]:
df.head(5)

,Datetime,CO2_1_1_1 [Tower 2],H2O_1_1_1 [Tower 2],CH4_1_1_1 [Tower 2],TAU_1_1_1 [Tower 2],TAU_SSITC_TEST_1_1_1 [Tower 2],H_1_1_1 [Tower 2],H_SSITC_TEST_1_1_1 [Tower 2],LE_1_1_1 [Tower 2],LE_SSITC_TEST_1_1_1 [Tower 2],...,W m-2.27,m^3/m^3.6,m^3/m^3.7,m^3/m^3.8,W m-2.28,W m-2.29,K.8,K.9,K.10,K.11
0,2017/01/01 00:30:00,373.002829,2.582062,NaN,0.069802,0.0,-17.133901,0.0,0.674787,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2017/01/01 01:00:00,371.852183,2.612844,NaN,0.113796,0.0,-29.551981,0.0,1.421192,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2017/01/01 01:30:00,370.031688,2.637917,NaN,0.100904,0.0,-27.296196,0.0,1.273268,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2017/01/01 02:00:00,370.166670,2.715083,NaN,0.076227,0.0,-22.312671,0.0,1.493439,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2017/01/01 02:30:00,372.749172,2.548190,NaN,0.110068,0.0,-15.307297,1.0,6.153345,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN